'use client';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from "@/components/container";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

/*
export const metadata: Metadata = {
  title: "Jibu Inc – Local Owners Driving Lasting Solutions",
  description: "Generated by create next app",
};

*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()
  const noLayoutRoutes = ['/uganda', '/kenya', '/burundi', '/kenya', '/tanzania', '/zambia', '/rwanda', '/drc', '/ghana']; //this is layout for global site. We dont want this to apply to country sites.
  const hideLayout = noLayoutRoutes.some(route => pathname.startsWith(route));
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-200`}>
        <Container>
          {!hideLayout && <Header />}
          {children}
          {!hideLayout && <Footer />}
        </Container>
      </body>
    </html>
  );
}


